Controllers/ExportToExcelController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using ClosedXML.Excel;

namespace Coffee_Shop.Controllers
{
    public class ExportToExcelController : Controller
    {
        private IConfiguration _configuration;
        public ExportToExcelController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #region ExportToExcel
        public IActionResult ExportToExcel(string table)
        {
            string str = _configuration.GetConnectionString("ConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = $"pr_{table}_SelectAll";

            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);
            if (dt.Rows.Count > 0)
            {
                dt.TableName = table;
                using (XLWorkbook workbook = new XLWorkbook())
                {
                    var ws = workbook.Worksheets.Add(dt, table);
                    ws.Columns();
                    ws.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Style.Font.Bold = true;

                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        workbook.SaveAs(memoryStream);
                        memoryStream.Position = 0;
                        return File(memoryStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{table}List.xlsx");
                    }
                }
            }
            return View();
        }
        #endregion
    }
}

Controllers/OrderDetailController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using Admin_Panel__Nice_Admin_.Models;
using Coffee_Shop_Management_System_Admin_Panel_.BAL;
using Microsoft.Extensions.Configuration;

namespace Admin_Panel__Nice_Admin_.Controllers
{
    [CheckAccess]
    public class OrderDetailController : Controller
    {
        private IConfiguration configuration;

        public OrderDetailController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region UserDropDown
        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> UserList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel UserDropDownModel = new UserDropDownModel();
                UserDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                UserDropDownModel.UserName = data["UserName"].ToString();
                UserList.Add(UserDropDownModel);
            }
            ViewBag.UserList = UserList;
        }
        #endregion

        #region SelectAll
        public IActionResult Orderdetails()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_OrderDetail_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            if (reader.HasRows)
            {
                table.Load(reader);
            }
            return View(table);
        }
        #endregion

        #region Delete
        public IActionResult OrderDelete(int OrderDetailID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_OrderDetail_Delete";
                command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = OrderDetailID;
                command.ExecuteNonQuery();
                if (command.ExecuteNonQuery() > 0)
                {
                    TempData["ErrorMessage"] = "Record Not Deleted";
                }
                else
                {
                    TempData["Message"] = "Record Deleted Successfully";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("Orderdetails");
        }
        #endregion

        #region PopulateDropDowns
        private void PopulateDropDowns()
        {
            string connectionString = configuration.GetConnectionString("ConnectionString");

            List<ProductDropDownModel> productList = new List<ProductDropDownModel>();
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();

            #region DropdownProductID
            SqlConnection connectionProduct = new SqlConnection(connectionString);
            SqlCommand commandProduct = new SqlCommand("PR_Product_DropDown", connectionProduct);
            commandProduct.CommandType = CommandType.StoredProcedure;

            try
            {
                connectionProduct.Open();
                SqlDataReader readerProduct = commandProduct.ExecuteReader();
                DataTable dataTableProduct = new DataTable();
                dataTableProduct.Load(readerProduct);

                foreach (DataRow row in dataTableProduct.Rows)
                {
                    ProductDropDownModel productDropDownModel = new ProductDropDownModel
                    {
                        ProductID = Convert.ToInt32(row["ProductID"]),
                        ProductName = row["ProductName"].ToString()
                    };
                    productList.Add(productDropDownModel);
                }
            }
            finally
            {
                connectionProduct.Close();
            }
            #endregion

            #region DropdownOrderID
            SqlConnection connectionOrder = new SqlConnection(connectionString);
            SqlCommand commandOrder = new SqlCommand("PR_Order_DropDown", connectionOrder);
            commandOrder.CommandType = CommandType.StoredProcedure;

            try
            {
                connectionOrder.Open();
                SqlDataReader readerOrder = commandOrder.ExecuteReader();
                DataTable dataTableOrder = new DataTable();
                dataTableOrder.Load(readerOrder);

                foreach (DataRow row in dataTableOrder.Rows)
                {
                    OrderDropDownModel orderDropDownModel = new OrderDropDownModel
                    {
                        OrderID = Convert.ToInt32(row["OrderID"])
                    };
                    orderList.Add(orderDropDownModel);
                }
            }
            finally
            {
                connectionOrder.Close();
            }
            #endregion

            ViewBag.ProductList = productList;
            ViewBag.OrderList = orderList;
        }
        #endregion

        #region Add or Edit
        public IActionResult AddOrderDetail(int? orderDetailID)
        {
            OrderDetailModel orderDetailModel = new OrderDetailModel();

            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "[dbo].[PR_OrderDetail_SelectByPK]";
            command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = (object)orderDetailID ?? DBNull.Value;

            try
            {
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                if (reader.HasRows && orderDetailID != null)
                {
                    reader.Read();
                    orderDetailModel.OrderDetailID = Convert.ToInt32(reader["OrderDetailID"]);
                    orderDetailModel.OrderID = Convert.ToInt32(reader["OrderID"]);
                    orderDetailModel.ProductID = Convert.ToInt32(reader["ProductID"]);
                    orderDetailModel.Quantity = Convert.ToInt32(reader["Quantity"]);
                    orderDetailModel.Amount = Convert.ToDecimal(reader["Amount"]);
                    orderDetailModel.TotalAmount = Convert.ToDecimal(reader["TotalAmount"]);
                    orderDetailModel.UserID = Convert.ToInt32(reader["UserID"]);
                }
            }
            finally
            {
                UserDropDown();
                PopulateDropDowns();
                connection.Close();
            }

            return View(orderDetailModel);
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(OrderDetailModel modelOrderDetail)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;

            if (modelOrderDetail.OrderDetailID == null)
            {
                command.CommandText = "[dbo].[PR_OrderDetail_Insert]";
            }
            else
            {
                command.CommandText = "[dbo].[PR_OrderDetail_Update]";
                command.Parameters.Add("@OrderDetailID", SqlDbType.Int).Value = modelOrderDetail.OrderDetailID;
            }

            command.Parameters.Add("@OrderID", SqlDbType.Int).Value = modelOrderDetail.OrderID;
            command.Parameters.Add("@ProductID", SqlDbType.Int).Value = modelOrderDetail.ProductID;
            command.Parameters.Add("@Quantity", SqlDbType.Int).Value = modelOrderDetail.Quantity;
            command.Parameters.Add("@Amount", SqlDbType.Decimal).Value = modelOrderDetail.Amount;
            command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = modelOrderDetail.TotalAmount;
            command.Parameters.Add("@UserID", SqlDbType.Int).Value = modelOrderDetail.UserID;

            try
            {
                connection.Open();
                int result = command.ExecuteNonQuery();

                if (result > 0)
                {
                    TempData["Message"] = modelOrderDetail.OrderDetailID == null ? "Record Inserted Successfully" : "Record Updated Successfully";
                }
            }
            finally
            {
                UserDropDown();
                PopulateDropDowns();
                connection.Close();
            }

Views/OrderDetail/AddOrderDetail.cshtml
@{
    ViewData["Title"] = "Add OrderDetail Page";
}

@model OrderDetailModel

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Add Order</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active">Add OrderDetail</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">OrderDetails</h5>
                    <h4 class="font-green-sharp">@TempData["Message"]</h4>
                    <!-- Multi Columns Form -->
                    <form class="row g-3" method="post" asp-controller="OrderDetail" asp-action="Save">
                        @if (Model.OrderDetailID != null)
                        {
                            <input type="hidden" asp-for="OrderDetailID" />
                        }                      
                        <div class="col-md-12">
                            <label for="OrderID" class="form-label"><span class="text-danger">*</span>Order</label>
                            <select class="form-control" asp-for="OrderID" asp-items="@(ViewBag.OrderList != null ? new SelectList(ViewBag.OrderList, "OrderID", "OrderID") : null)">
                                <option value="">Select Order</option>
                            </select>
                            <span asp-validation-for="OrderID" class="text-danger"></span>
                        </div>
                        <div class="col-md-12">
                            <label for="ProductID" class="form-label"><span class="text-danger">*</span>Product ID</label>
                            <select class="form-control" id="ProductID" asp-for="ProductID" asp-items="@(ViewBag.ProductList != null ? new SelectList(ViewBag.ProductList, "ProductID", "ProductName") : null)">
                                <option value="">Select Product</option>
                            </select>
                            <span asp-validation-for="ProductID" class="text-danger"></span>
                        </div>
                        <div class="col-12">
                            <label for="Quantity" class="form-label"><span class="text-danger">*</span>Quantity</label>
                            <input type="number" class="form-control" asp-for="Quantity" id="Quantity" placeholder="Enter Quantity">
                            <span asp-validation-for="Quantity" class="text-danger"></span>
                        </div>
                        <div class="col-12">
                            <label for="Amount" class="form-label"><span class="text-danger">*</span>Amount</label>
                            <input type="number" class="form-control" asp-for="Amount" id="Amount" placeholder="Enter Amount">
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                        <div class="col-12">
                            <label for="TotalAmount" class="form-label"><span class="text-danger">*</span>Total Amount</label>
                            <input type="number" class="form-control" asp-for="TotalAmount" id="TotalAmount" placeholder="Enter TotalAmount">
                            <span asp-validation-for="TotalAmount" class="text-danger"></span>
                        </div>
                        <div class="col-md-12">
                            <label for="UserID" class="form-label"><span class="text-danger">*</span>UserName</label> 
                            <select class="form-control" asp-for="UserID">
                                <option value="">select user</option>
                                @foreach (var user in ViewBag.UserList)
                                {
                                    <option value="@user.UserID">@user.UserName</option>
                                }
                            </select>
                            <span asp-validation-for="UserID" class="text-danger"></span>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a class="btn btn-secondary" asp-controller="OrderDetail" asp-action="OrderDetails">Cancel</a>
                        </div>
                    </form><!-- End Multi Columns Form -->

                </div>
            </div>
        </div>
    </div>

</main>

Views/OrderDetail/Orderdetails.cshtml
@{
    ViewData["Title"] = "Order Details Page";
}

@using System.Data
@model DataTable

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Data Tables</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active">Order Details</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <h5 class="card-title">Order List</h5>
                            <div>
                                <a class="btn btn-outline-primary" asp-controller="ExportToExcel" asp-action="ExportToExcel" asp-route-table="Orderdetail">
                                    <i class="bi bi-filetype-xlsx"></i>Export
                                </a>
                            </div>
                        </div>                   
                        <h6 class="text-success">
                            @if (TempData["Message"] != null)
                            {
                                <div class="alert alert-success text-success">
                                    @TempData["Message"]
                                </div>
                            }
                            @if (TempData["ErrorMessage"] != null)
                            {
                                <div class="alert alert-danger text-danger">
                                    @TempData["ErrorMessage"]
                                </div>
                            }
                        </h6>
                        <div class="table-responsive">
                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>
                                            <b>O</b>rderDetail_ID
                                        </th>
                                        <th>Order_ID</th>
                                        <th>Product_ID</th>                                        
                                        <th>Quantity</th>
                                        <th>Amount</th>
                                        <th>Total Amount</th>                                       
                                        <th>User_ID</th>
                                        <th colspan="2">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Rows.Count > 0) {
                                        @foreach (DataRow dr in Model.Rows) 
                                        {
                                            <tr class="text-center">
                                                <td>@dr["OrderDetailID"]</td>
                                                <td>@dr["OrderID"]</td>
                                                <td>@dr["ProductID"]</td>
                                                <td>@dr["Quantity"]</td>
                                                <td>@dr["Amount"]</td>
                                                <td>@dr["TotalAmount"]</td>  
                                                <td>@dr["UserID"]</td>
                                                <td class="d-flex">
                                                    @* <button class="btn btn-warning">Edit</button> *@
                                                    <a class="btn btn-warning btn-sm me-2" asp-controller="OrderDetail" asp-action="AddOrderDetail" asp-route-OrderDetailID="@dr["OrderDetailID"]">
                                                        <i class="bi bi-pencil-fill"></i>
                                                    </a>
                                                    <span class="btn btn-danger btn-sm" onclick="confirmDelete(@dr["OrderDetailID"])">
                                                        <i class="bi bi-x"></i>
                                                    </span>
                                                    @* <button class="btn btn-danger">Delete</button> *@
                                                </td>
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="5" class="text-center">
                                                <p class="col-form-label">No Record Found</p>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- End Table with stripped rows -->
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->

<script>
    function confirmDelete(OrderDetailID) {
        if (confirm('Are you sure you want to delete this user ? ')) {
            window.location.href = "/OrderDetail/OrderDelete?OrderDetailID=" + OrderDetailID;
        }
    }
</script>