Controllers/ExportToExcelController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using ClosedXML.Excel;

namespace Coffee_Shop.Controllers
{
    public class ExportToExcelController : Controller
    {
        private IConfiguration _configuration;
        public ExportToExcelController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #region ExportToExcel
        public IActionResult ExportToExcel(string table)
        {
            string str = _configuration.GetConnectionString("ConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = $"pr_{table}_SelectAll";

            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);
            if (dt.Rows.Count > 0)
            {
                dt.TableName = table;
                using (XLWorkbook workbook = new XLWorkbook())
                {
                    var ws = workbook.Worksheets.Add(dt, table);
                    ws.Columns();
                    ws.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Style.Font.Bold = true;

                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        workbook.SaveAs(memoryStream);
                        memoryStream.Position = 0;
                        return File(memoryStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{table}List.xlsx");
                    }
                }
            }
            return View();
        }
        #endregion
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using Admin_Panel__Nice_Admin_.Models;
using Coffee_Shop_Management_System_Admin_Panel_.BAL;

namespace Admin_Panel__Nice_Admin_.Controllers
{
    [CheckAccess]
    public class OrderController : Controller
    {
        private IConfiguration configuration;

        public OrderController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult Index()
        {
            return View();
        }

        #region UserDropDown
        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> UserList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel UserDropDownModel = new UserDropDownModel();
                UserDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                UserDropDownModel.UserName = data["UserName"].ToString();
                UserList.Add(UserDropDownModel);
            }
            ViewBag.UserList = UserList;
        }
        #endregion

        #region AddOrder
        public IActionResult AddOrder(int? OrderID = null)
        {
            OrderModel modelOrder = new OrderModel();
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            #region Dropdown
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = CommandType.StoredProcedure;
            command1.CommandText = "PR_Customer_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(reader1);
            List<CustomerDropDownModel> customerList = new List<CustomerDropDownModel>();
            foreach (DataRow dataRow in dataTable.Rows)
            {
                CustomerDropDownModel customerDropDownModel = new CustomerDropDownModel
                {
                    CustomerID = Convert.ToInt32(dataRow["CustomerID"]),
                    CustomerName = dataRow["CustomerName"].ToString()
                };
                customerList.Add(customerDropDownModel);
            }
            ViewBag.CustomerList = customerList;
            connection1.Close();
            #endregion

            UserDropDown();

            #region AddEdit
            if (OrderID != null)
            {
                SqlConnection connection2 = new SqlConnection(connectionString);
                connection2.Open();
                SqlCommand command2 = connection2.CreateCommand();
                command2.CommandType = CommandType.StoredProcedure;
                command2.CommandText = "[dbo].[PR_Order_SelectByPK]";
                command2.Parameters.Add("@OrderID", SqlDbType.Int).Value = OrderID;

                SqlDataReader reader2 = command2.ExecuteReader();
                if (reader2.HasRows)
                {
                    reader2.Read();
                    modelOrder.OrderID = Convert.ToInt32(reader2["OrderID"]);
                    modelOrder.OrderDate = Convert.ToDateTime(reader2["OrderDate"]);
                    modelOrder.CustomerID = Convert.ToInt32(reader2["CustomerID"]);
                    modelOrder.PaymentMode = reader2["PaymentMode"].ToString();
                    modelOrder.TotalAmount = Convert.ToDecimal(reader2["TotalAmount"]);
                    modelOrder.ShippingAddress = reader2["ShippingAddress"].ToString();
                    modelOrder.UserID = Convert.ToInt32(reader2["UserID"]);
                }
                connection2.Close();
            }
            return View(modelOrder);
            #endregion
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(OrderModel modelOrder)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;

            if (modelOrder.OrderID == null)
            {
                command.CommandText = "[dbo].[PR_Order_Insert]";
            }
            else
            {
                command.CommandText = "[dbo].[PR_Order_Update]";
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = modelOrder.OrderID;
            }

            command.Parameters.Add("@OrderDate", SqlDbType.DateTime).Value = modelOrder.OrderDate;
            command.Parameters.Add("@CustomerID", SqlDbType.Int).Value = modelOrder.CustomerID;
            command.Parameters.Add("@PaymentMode", SqlDbType.VarChar).Value = modelOrder.PaymentMode;
            command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = modelOrder.TotalAmount;
            command.Parameters.Add("@ShippingAddress", SqlDbType.VarChar).Value = modelOrder.ShippingAddress;
            command.Parameters.Add("@UserID", SqlDbType.Int).Value = modelOrder.UserID;

            int result = command.ExecuteNonQuery();
            if (result > 0)
            {
                TempData["Message"] = modelOrder.OrderID == null ? "Record Inserted Successfully" : "Record Updated Successfully";
            }

            #region Dropdown
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = CommandType.StoredProcedure;
            command1.CommandText = "PR_Customer_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(reader1);
            List<CustomerDropDownModel> customerList = new List<CustomerDropDownModel>();
            foreach (DataRow dataRow in dataTable.Rows)
            {
                CustomerDropDownModel customerDropDownModel = new CustomerDropDownModel
                {
                    CustomerID = Convert.ToInt32(dataRow["CustomerID"]),
                    CustomerName = dataRow["CustomerName"].ToString()
                };
                customerList.Add(customerDropDownModel);
            }
            ViewBag.CustomerList = customerList;
            connection1.Close();
            #endregion

            UserDropDown();

            connection.Close();

            return RedirectToAction("Orderdetail");
        }
        #endregion

        #region Delete
        public IActionResult OrderDelete(int OrderID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "[dbo].[PR_Order_Delete]";
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = OrderID;
                command.ExecuteNonQuery();
                if (command.ExecuteNonQuery() > 0)
                {
                    TempData["ErrorMessage"] = "Record Not Deleted";
                }
                else
                {
                    TempData["Message"] = "Record Deleted Successfully";
                }
                connection.Close();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Cannot delete this Order because it is associated with a user. Please delete the associated user first.";
            }
            return RedirectToAction("Orderdetail");
        }
        #endregion

        #region SelectALL
        public IActionResult Orderdetail()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_Order_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            if (reader.HasRows)
            {
                table.Load(reader);
            }
            return View(table);
        }
        #endregion

    }
}

Views/Order/AddOrder.cshtml
@{
    ViewData["Title"] = "Add Order Page";
}

@model OrderModel;

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Add Order</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active">Add Order</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Order</h5>
                    <h4 class="font-green-sharp">@TempData["Message"]</h4>
                    <!-- Multi Columns Form -->
                    <form class="row g-3" method="post" asp-controller="Order" asp-action="Save">

                        @if (Model.OrderID != null)
                        {
                            <input type="hidden" asp-for="OrderID" />
                        }

                        <div class="col-md-12">
                            <label for="OrderDate" class="form-label"><span class="text-danger">*</span>Order Date </label>
                            <input type="date" class="form-control" asp-for="OrderDate" id="OrderDate" name="OrderDate" />
                            <span asp-validation-for="OrderDate" class="text-danger"></span>
                        </div>

                        <div class="col-md-12">
                            <label for="CustomerID" class="form-label"><span class="text-danger">*</span>Customer ID</label>
                            <select class="form-control" id="CustomerID" asp-for="CustomerID" asp-items="@(new SelectList(ViewBag.CustomerList, "CustomerID", "CustomerName"))">
                                <option value="">Select Customer</option>
                            </select>
                            <span asp-validation-for="CustomerID" class="text-danger"></span>
                        </div>

                        <div class="col-12">
                            <label for="PaymentMode" class="form-label"><span class="text-danger">*</span>Payment Mode</label>
@*                             <input type="text" class="form-control" asp-for="PaymentMode" id="PaymentMode" placeholder="Enter PaymentMode" /> *@
                            <select class="form-control" asp-for="PaymentMode">
                                <option value="">Select PaymentMode</option>
                                <option value="Credit Card">Credit Card</option>
                                <option value="Debit Card">Debit Card</option>
                                <option value="Cash on Delivery">Cash on Delivery</option>
                            </select>
                            <span asp-validation-for="PaymentMode" class="text-danger"></span>
                        </div>

                        <div class="col-12">
                            <label for="TotalAmount" class="form-label"><span class="text-danger">*</span>Total Amount</label>
                            <input type="number" class="form-control" asp-for="TotalAmount" id="TotalAmount" placeholder="Enter Total_Amount">
                            <span asp-validation-for="TotalAmount" class="text-danger"></span>
                        </div>

                        <div class="col-12">
                            <label for="ShippingAddress" class="form-label"><span class="text-danger">*</span>Shipping Address</label>
                            <input type="text" class="form-control" asp-for="ShippingAddress" id="ShippingAddress" placeholder="Enter ShippingAddress">
                            <span asp-validation-for="ShippingAddress" class="text-danger"></span>
                        </div>

                        <div class="col-md-12">                          
                            <label for="UserID" class="form-label"><span class="text-danger">*</span>UserName</label>
                            <select class="form-control" asp-for="UserID">
                                <option value="">Select User</option>
                                @foreach (var User in ViewBag.UserList)
                                {
                                    <option value="@User.UserID">@User.UserName</option>
                                }
                            </select>
                            <span asp-validation-for="UserID" class="text-danger"></span>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a class="btn btn-secondary" asp-controller="Order" asp-action="Orderdetail">Cancel</a>
                        </div>
                    </form><!-- End Multi Columns Form -->
                </div>
            </div>
        </div>
    </div>
</main>

Views/Order/Orderdetail.cshtml
@{
    ViewData["Title"] = "Order Page";
}

@using System.Data
@model DataTable

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Data Tables</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active">Order Details</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <h5 class="card-title">Order List</h5>
                            <div>
                                <a class="btn btn-outline-primary" asp-controller="ExportToExcel" asp-action="ExportToExcel" asp-route-table="Order">
                                    <i class="bi bi-filetype-xlsx"></i>Export
                                </a>
                            </div>
                        </div>
                        
                        <h6 class="text-success">
                            @if (TempData["Message"] != null)
                            {
                                <div class="alert alert-success text-success">
                                    @TempData["Message"]
                                </div>
                            }
                            @if (TempData["ErrorMessage"] != null)
                            {
                                <div class="alert alert-danger text-danger">
                                    @TempData["ErrorMessage"]
                                </div>
                            }
                        </h6>
                        <div class="table-responsive">
                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>
                                            <b>O</b>rder_Id
                                        </th>
                                        <th data-type="date" data-format="YYYY/DD/MM">Order_Date</th>
                                        <th>Customer_Id</th>
                                        <th>Payment Mode</th>
                                        <th>Total Amount</th>
                                        <th>Shipping Address</th>
                                        <th>User_ID</th>
                                        <th colspan="2">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Rows.Count > 0) {
                                        @foreach (DataRow dr in Model.Rows)
                                        {
                                            <tr class="text-center">
                                                <td>@dr["OrderID"]</td>
                                                <td>@dr["OrderDate"]</td>
                                                <td>@dr["CustomerID"]</td>
                                                <td>@dr["PaymentMode"]</td>
                                                <td>@dr["TotalAmount"]</td>
                                                <td>@dr["ShippingAddress"]</td>  
                                                <td>@dr["UserId"]</td>
                                                <td class="d-flex">
                                                    @* <button class="btn btn-warning">Edit</button> *@
                                                    <a class="btn btn-warning btn-sm me-2" asp-controller="Order" asp-action="AddOrder" asp-route-OrderID="@dr["OrderID"]">
                                                        <i class="bi bi-pencil-fill"></i>
                                                    </a>
                                                    <span class="btn btn-danger btn-sm" onclick="confirmDelete(@dr["OrderID"])">
                                                        <i class="bi bi-x"></i>
                                                    </span>
                                                    @* <button class="btn btn-danger">Delete</button> *@
                                                </td>
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="5" class="text-center">
                                                <p class="col-form-label">No Record Found</p>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- End Table with stripped rows -->
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->

<script>
    function confirmDelete(OrderID) {
        if (confirm('Are you sure you want to delete this user ? ')) {
            window.location.href = "/Order/OrderDelete?OrderID=" + OrderID;
        }
    }
</script>