Controllers/BillsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using Admin_Panel__Nice_Admin_.Models;
using Coffee_Shop_Management_System_Admin_Panel_.BAL;

namespace Admin_Panel__Nice_Admin_.Controllers
{
    [CheckAccess]
    public class BillsController : Controller
    {
        private IConfiguration configuration;

        public BillsController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region UserDropDown
        public void UserDropDown()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            connection1.Open();
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> UserList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel UserDropDownModel = new UserDropDownModel();
                UserDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                UserDropDownModel.UserName = data["UserName"].ToString();
                UserList.Add(UserDropDownModel);
            }
            ViewBag.UserList = UserList;
        }
        #endregion

        #region AddEdit
        public IActionResult AddBill(int? billID)
        {
            UserDropDown();
            string connectionString = configuration.GetConnectionString("ConnectionString");
            SqlConnection connection1 = new SqlConnection(connectionString);
            SqlCommand command1 = connection1.CreateCommand();
            command1.CommandType = CommandType.StoredProcedure;
            command1.CommandText = "PR_Order_DropDown";

            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();

            try
            {
                connection1.Open();
                SqlDataReader reader1 = command1.ExecuteReader();
                DataTable dataTable1 = new DataTable();
                dataTable1.Load(reader1);

                foreach (DataRow dataRow in dataTable1.Rows)
                {
                    OrderDropDownModel orderDropDownModel = new OrderDropDownModel
                    {
                        OrderID = Convert.ToInt32(dataRow["OrderID"])
                    };
                    orderList.Add(orderDropDownModel);
                }
                ViewBag.orderList = orderList;
            }
            finally
            {
                connection1.Close();
            }

            BillsModel modelBills = new BillsModel();
            SqlConnection connection2 = new SqlConnection(connectionString);
            SqlCommand command2 = connection2.CreateCommand();
            command2.CommandType = CommandType.StoredProcedure;
            command2.CommandText = "[dbo].[PR_Bills_SelectByPK]";
            command2.Parameters.Add("@BillID", SqlDbType.Int).Value = (object)billID ?? DBNull.Value;
            try
            {
                connection2.Open();
                SqlDataReader reader2 = command2.ExecuteReader();

                if (reader2.HasRows && billID != null)
                {
                    reader2.Read();
                    modelBills.BillID = Convert.ToInt32(reader2["BillID"]);
                    modelBills.BillNumber = reader2["BillNumber"].ToString();
                    modelBills.BillDate = Convert.ToDateTime(reader2["BillDate"]);
                    modelBills.OrderID = Convert.ToInt32(reader2["OrderID"]);
                    modelBills.TotalAmount = Convert.ToDecimal(reader2["TotalAmount"]);
                    modelBills.Discount = Convert.ToDecimal(reader2["Discount"]);
                    modelBills.NetAmount = Convert.ToDecimal(reader2["NetAmount"]);
                    modelBills.UserID = Convert.ToInt32(reader2["UserID"]);
                }
            }
            finally
            {
                connection2.Close();
            }

            return View(modelBills);
        }
        #endregion

        #region Save
        [HttpPost]
        public IActionResult Save(BillsModel modelBills)
        {
            string connectionString = configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;

            if (modelBills.BillID == null)
            {
                command.CommandText = "[dbo].[PR_Bills_Insert]";
            }
            else
            {
                command.CommandText = "[dbo].[PR_Bills_Update]";
                command.Parameters.Add("@BillID", SqlDbType.Int).Value = modelBills.BillID;
            }

            command.Parameters.Add("@BillNumber", SqlDbType.VarChar).Value = modelBills.BillNumber;
            command.Parameters.Add("@BillDate", SqlDbType.DateTime).Value = modelBills.BillDate;
            command.Parameters.Add("@OrderID", SqlDbType.Int).Value = modelBills.OrderID;
            command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = modelBills.TotalAmount;
            command.Parameters.Add("@Discount", SqlDbType.Decimal).Value = modelBills.Discount;
            command.Parameters.Add("@NetAmount", SqlDbType.Decimal).Value = modelBills.NetAmount;
            command.Parameters.Add("@UserID", SqlDbType.Int).Value = modelBills.UserID;

            try
            {
                connection.Open();
                if (command.ExecuteNonQuery() > 0)
                {
                    TempData["Message"] = modelBills.BillID == null ? "Record Inserted Successfully" : "Record Updated Successfully";
                }
            }
            finally
            {
                connection.Close();
            }

            return RedirectToAction("Billsdetail");
        }
        #endregion

        #region Delete
        public IActionResult BillsDelete(int BillID)
        {
            try
            {
                string connectionString = configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "[dbo].[PR_Bills_Delete]";
                command.Parameters.Add("@BillID", SqlDbType.Int).Value = BillID;
                command.ExecuteNonQuery();
                if (command.ExecuteNonQuery() > 0)
                {
                    TempData["ErrorMessage"] = "Record Not Deleted";
                }
                else
                {
                    TempData["Message"] = "Record Deleted Successfully";
                }
                connection.Close();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Cannot delete this Order because it is associated with a user. Please delete the associated user first.";
            }
            return RedirectToAction("Billsdetail");
        }
        #endregion

        #region SelectAll
        public IActionResult Billsdetail()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_Bills_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
            if (reader.HasRows)
            {
                table.Load(reader);
            }
            return View(table);
        }
        #endregion
    }
}

Controllers/ExportToExcelController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using ClosedXML.Excel;

namespace Coffee_Shop.Controllers
{
    public class ExportToExcelController : Controller
    {
        private IConfiguration _configuration;
        public ExportToExcelController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #region ExportToExcel
        public IActionResult ExportToExcel(string table)
        {
            string str = _configuration.GetConnectionString("ConnectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = $"pr_{table}_SelectAll";

            DataTable dt = new DataTable();
            SqlDataReader sdr = cmd.ExecuteReader();
            dt.Load(sdr);
            if (dt.Rows.Count > 0)
            {
                dt.TableName = table;
                using (XLWorkbook workbook = new XLWorkbook())
                {
                    var ws = workbook.Worksheets.Add(dt, table);
                    ws.Columns();
                    ws.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    ws.Style.Font.Bold = true;

                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        workbook.SaveAs(memoryStream);
                        memoryStream.Position = 0;
                        return File(memoryStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{table}List.xlsx");
                    }
                }
            }
            return View();
        }
        #endregion
    }
}

Views/Bills/AddBill.cshtml
@{
    ViewData["Title"] = "Add Bill Page";
}

@model BillsModel

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Add Order</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active">Add Bill</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Bills</h5>
                    <h4 class="font-green-sharp">@TempData["Message"]</h4>
                    <!-- Multi Columns Form -->
                    <form class="row g-3" asp-action="Save" asp-controller="Bills">
                        @if (Model.BillID != null)
                        {
                            <input type="hidden" asp-for="BillID" />
                        }
                        <div class="col-md-12">
                            <label for="BillNumber" class="form-label"><span class="text-danger">*</span>Bill Number</label>                           
                            <input type="text" class="form-control" asp-for="BillNumber" id="BillNumber" />
                            <span asp-validation-for="BillNumber" class="text-danger"></span>
                        </div>
                        <div class="col-md-12">
                            <label for="BillDate" class="form-label"><span class="text-danger">*</span>Bill Date</label>
                            <input type="date" class="form-control" asp-for="BillDate" id="BillDate" />
                            <span asp-validation-for="BillDate" class="text-danger"></span>
                        </div>
                        
                        <div class="col-12">
                            <label for="OrderID" class="form-label"><span class="text-danger">*</span>Order ID</label>
                            <select class="form-control" id="OrderID" asp-for="OrderID" asp-items="@(new SelectList(ViewBag.OrderList, "OrderID", "OrderID"))">
                                <option value="">Select Order</option>
                            </select>
                            <span asp-validation-for="OrderID" class="text-danger"></span>
                        </div>
                        <div class="col-12">
                            <label for="TotalAmount" class="form-label"><span class="text-danger">*</span>Total Amount</label>
                            <input type="number" class="form-control" asp-for="TotalAmount" id="TotalAmount" />
                            <span asp-validation-for="TotalAmount" class="text-danger"></span>
                        </div>
                        <div class="col-12">
                            <label for="Discount" class="form-label"><span class="text-danger">*</span>Discount</label>
                            <input type="text" class="form-control" asp-for="Discount" id="Discount" />
                            <span asp-validation-for="Discount" class="text-danger"></span>
                        </div>
                        <div class="col-12">
                            <label for="NetAmount" class="form-label"><span class="text-danger">*</span>Net Amount</label>
                            <input type="number" class="form-control" asp-for="NetAmount" id="NetAmount" />
                            <span asp-validation-for="NetAmount" class="text-danger"></span>
                        </div>
                        <div class="col-md-12">
                            <label for="UserID" class="form-label"><span class="text-danger">*</span>UserName</label>
                            <select class="form-control" asp-for="UserID">
                                <option value="">Select User</option>
                                @foreach (var User in ViewBag.UserList)
                                {
                                    <option value="@User.UserID">@User.UserName</option>
                                }
                            </select>
                            <span asp-validation-for="UserID" class="text-danger"></span>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <a class="btn btn-secondary" asp-controller="Bills" asp-action="Billsdetail">Cancel</a>
                        </div>
                    </form><!-- End Multi Columns Form -->

                </div>
            </div>
        </div>
    </div>

</main>

Views/Bills/Billsdetail.cshtml
@{
    ViewData["Title"] = "Bills Page";
}

@using System.Data
@model DataTable

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Data Tables</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item active">Bills Details</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <h5 class="card-title">Bills List</h5>
                            <div>
                                <a class="btn btn-outline-primary" asp-controller="ExportToExcel" asp-action="ExportToExcel" asp-route-table="Bills">
                                    <i class="bi bi-filetype-xlsx"></i>Export
                                </a>
                            </div>
                        </div>             
                        <h6 class="text-success">
                            @if (TempData["Message"] != null)
                            {
                                <div class="alert alert-success text-success">
                                    @TempData["Message"]
                                </div>
                            }
                            @if (TempData["ErrorMessage"] != null)
                            {
                                <div class="alert alert-danger text-danger">
                                    @TempData["ErrorMessage"]
                                </div>
                            }
                        </h6>
                        <div class="table-responsive">
                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>
                                            <b>B</b>ill_ID
                                        </th>
                                        <th>Bill Number</th>
                                        <th data-type="date" data-format="YYYY/DD/MM">Bill Number</th>
                                        <th>Order_ID</th>
                                        <th>Total Amount</th>
                                        <th>Discount</th>
                                        <th>Net Amount</th>
                                        <th>User_ID</th>
                                        <th colspan="2">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Rows.Count > 0) {
                                        @foreach (DataRow dr in Model.Rows)
                                        {
                                            <tr class="text-center  ">
                                                <td>@dr["BillID"]</td>
                                                <td>@dr["BillNumber"]</td>
                                                <td>@dr["BillDate"]</td>
                                                <td>@dr["OrderID"]</td>
                                                <td>@dr["TotalAmount"]</td>
                                                <td>@dr["Discount"]</td>  
                                                <td>@dr["NetAmount"]</td>
                                                <td>@dr["UserID"]</td>
                                                <td class="d-flex">
                                                    @* <button class="btn btn-warning">Edit</button> *@
                                                    <a class="btn btn-warning btn-sm me-2" asp-controller="Bills" asp-action="AddBill" asp-route-BillID = "@dr["BillID"]">
                                                        <i class="bi bi-pencil-fill"></i>
                                                    </a>
                                                    <span class="btn btn-danger btn-sm" onclick="confirmDelete(@dr["BillID"])">
                                                        <i class="bi bi-x"></i>
                                                    </span>
                                                    @* <button class="btn btn-danger">Delete</button> *@
                                                </td>
                                            </tr>
                                        }  
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="5" class="text-center">
                                                <p class="col-form-label">No Record Found</p>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- End Table with stripped rows -->
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->

<script>
    function confirmDelete(BillID) {
        if (confirm('Are you sure you want to delete this user ? ')) {
            window.location.href = "/Bills/BillsDelete?BillID=" + BillID;
        }
    }
</script>